# Generated by Django 5.0.1 on 2024-01-26 07:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="logo_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
