# Generated by Django 5.0.1 on 2024-01-26 07:43

import job.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0002_job_logo_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=job.models.lowercase_filename
            ),
        ),
    ]
