# Generated by Django 5.0.1 on 2024-01-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("job", "0003_alter_job_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="new",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("open", "Open"), ("closed", "Closed")],
                max_length=100,
                null=True,
            ),
        ),
    ]
